version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=machina_labs
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - SERVICE_TAGS=prod
      - SERVICE_NAME=db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
