version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=machina_labs
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - SERVICE_NAME=db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - internalnet

  nodeapp:
    container_name: machina_node_app
    build: ./server
    image: nodeapp:1.0
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=machina_labs
      - DB_CONNECTION_LIMIT=20
      - SERVER_PORT=8000
      - SERVICE_NAME=nodeapp
    depends_on:
      - db
    networks: 
     - internalnet

networks:
  internalnet:
    driver: bridge

